language: scala
sudo: false
scala:
- 2.11.7
- 2.10.5
jdk:
- openjdk7
- oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_JDK_VERSION = openjdk7 ]] &&
  [[ $TRAVIS_SCALA_VERSION = 2.11.* ]] &&
  pip install --user codecov && codecov
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_JDK_VERSION = openjdk7 ]] &&
  sbt ++$TRAVIS_SCALA_VERSION publishSnapshot
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_JDK_VERSION = openjdk7 ]] &&
  [[ $TRAVIS_SCALA_VERSION = 2.11.* ]] &&
  git config --global user.email "travis@travis-ci.org" &&
  git config --global user.name "Travis CI" &&
  git config --global push.default simple &&
  sbt makeSite ghpagesPushSite > /dev/null
env:
  global:
  - secure: eg/nDoGryerr4xT37aojC5M7YsOnWg0nct/8BJZcF4hd2aJh1kqqYEkwOKMHdVnGGdKy0dHK+mwSrefORcJBAzbV3yluQUgDDmFUVHqjsWhSzu12rBtMhmkaqNRvcznd/hHy509k6+RiQ7iFipE9idpEy3axUTTaWsMJPMLdzFg=
  - secure: qB5SyBNN9sXGBNdR2k5eTAykrEVEn/2CCi0Cx2Banli1S/+eYuytqTsxF2umhCe8pd+xn+IlfEresivSTQeXlaxGefU0Pd9Wq7a//Ha8qcHTQZ2YbISeAaNjAvy6WNf25rydLAYzW86CRTQJN4lswvAqkHvYyVuKPcyoxmwpDNw=
