language: scala
sudo: false
scala:
- 2.11.5
- 2.10.4
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_JDK_VERSION = oraclejdk8 ]] &&
  sbt ++$TRAVIS_SCALA_VERSION publishSnapshot
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_JDK_VERSION = oraclejdk8 ]] &&
  [[ $TRAVIS_SCALA_VERSION = 2.11.* ]] &&
  git config --global user.email "travis@travis-ci.org" &&
  git config --global user.name "Travis CI" &&
  sbt makeSite ghpagesPushSite
env:
  global:
  - secure: eg/nDoGryerr4xT37aojC5M7YsOnWg0nct/8BJZcF4hd2aJh1kqqYEkwOKMHdVnGGdKy0dHK+mwSrefORcJBAzbV3yluQUgDDmFUVHqjsWhSzu12rBtMhmkaqNRvcznd/hHy509k6+RiQ7iFipE9idpEy3axUTTaWsMJPMLdzFg=
  - secure: ozVqKEb9yqS+GdzcmBPx8wmQ7PSMdf9pPNHWAlL8GBLjXA9fgVTR/oJC5iKp+ktU5kU89dz2gWVtLuaSdJbMWtW1dmGH9ud+orZDc9FwMRtetQI3AUGCZDd8RWMb3flR59j27koWf5PSULwb8OvwH2EPzTQavahfVICusDzcyGE=
