language: scala
sudo: false
scala:
- 2.11.5
- 2.10.4
jdk:
- oraclejdk8
- oraclejdk7
- openjdk7
after_success:
- |
  test $TRAVIS_PULL_REQUEST == "false" &&
  test $TRAVIS_BRANCH == "master" &&
  test $TRAVIS_JDK_VERSION = "oraclejdk8" &&
  sbt ++$TRAVIS_SCALA_VERSION publishSnapshot
env:
  global:
  - secure: eg/nDoGryerr4xT37aojC5M7YsOnWg0nct/8BJZcF4hd2aJh1kqqYEkwOKMHdVnGGdKy0dHK+mwSrefORcJBAzbV3yluQUgDDmFUVHqjsWhSzu12rBtMhmkaqNRvcznd/hHy509k6+RiQ7iFipE9idpEy3axUTTaWsMJPMLdzFg=
