language: scala
sudo: false
matrix:
  include:
  - scala: 2.10.6
    jdk: openjdk6
  - scala: 2.11.8
    jdk: openjdk6
  - scala: 2.12.0
    jdk: oraclejdk8
script: sbt ++$TRAVIS_SCALA_VERSION validate
after_success:
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  sbt ++$TRAVIS_SCALA_VERSION publishSnapshot
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_SCALA_VERSION = 2.12.* ]] &&
  bash <(curl -s https://codecov.io/bash)
- |
  [[ $TRAVIS_PULL_REQUEST = false ]] &&
  [[ $TRAVIS_BRANCH = master ]] &&
  [[ $TRAVIS_SCALA_VERSION = 2.12.* ]] &&
  git config --global user.email "travis@travis-ci.org" &&
  git config --global user.name "Travis CI" &&
  git config --global push.default simple &&
  sbt makeSite ghpagesPushSite > /dev/null
env:
  global:
  - secure: eg/nDoGryerr4xT37aojC5M7YsOnWg0nct/8BJZcF4hd2aJh1kqqYEkwOKMHdVnGGdKy0dHK+mwSrefORcJBAzbV3yluQUgDDmFUVHqjsWhSzu12rBtMhmkaqNRvcznd/hHy509k6+RiQ7iFipE9idpEy3axUTTaWsMJPMLdzFg=
  - secure: qB5SyBNN9sXGBNdR2k5eTAykrEVEn/2CCi0Cx2Banli1S/+eYuytqTsxF2umhCe8pd+xn+IlfEresivSTQeXlaxGefU0Pd9Wq7a//Ha8qcHTQZ2YbISeAaNjAvy6WNf25rydLAYzW86CRTQJN4lswvAqkHvYyVuKPcyoxmwpDNw=
